services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - social-todo-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - social-todo:/var/lib/mysql
    networks:
      - social-todo-network

volumes:
  social-todo:

networks:
  social-todo-network:
    driver: bridge
